### ISSUE TITLE
[SUGGESTION] - Add a guide to README.md

### ISSUE THREAD

**Issue by NixV37** [Spacerulerwill/SpaceCases#2]
I saw there is a guide at CONTRIBUTING.md but It would be great to have a guide for someone that just wants to use the bot not to contribute :)

**Comment by Spacerulerwill** [comment]
Good idea. I wasn't planning on putting an invite link there yet but if people want to use it then I can put one. I will amend the readme soon with a mini guide. Bear in mind it is in beta and won't be up 100% of the time. Data might be wiped at random points.

**Comment by Spacerulerwill** [comment]
I have put the invite link on the readme. Invite to your server. There is a help command which should be useful for you!
